addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.3")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.9.13")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"                  % "2.1.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.11.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.10.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"              % "0.6.2")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"           % "1.5.9")
